CREATE DATABASE LIBROS_AUTORES

CREATE TABLE AUTORES(
IdAutor INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Nombre NVARCHAR(200) NOT NULL
)

CREATE TABLE LIBROS (
IdLibro INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
Titulo NVARCHAR(200) NOT NULL,
IdAutor INT NOT NULL
)

ALTER TABLE LIBROS
ADD FOREIGN KEY (IdAutor) REFERENCES AUTORES(IdAutor);


